package com.example.doctorkom.Entities;

public enum DoctorSpecialty {
    GENERAL_PRACTITIONER,
    CARDIOLOGIST,
    DERMATOLOGIST,
    PEDIATRICIAN,
    ORTHOPEDIC_SURGEON,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    NEUROLOGIST,
    UROLOGIST,
    ENT_SPECIALIST,
    PSYCHIATRIST,
    ONCOLOGIST,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    DENTAL_SURGEON
}
