CREATE TABLE Clinic(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    Address VARCHAR(50) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    Landline VARCHAR(20) NOT NULL
);
